### ISSUE TITLE
Space between Print buttons

### ISSUE THREAD

**Issue by sureshhewabi** [bezzlab/mzIdentMLVisualiser#13]

**Comment by sureshhewabi** [comment]
Changed CSS to:

``` css
.buttons-csv,
.buttons-print {
    margin-top: 20px;
    margin-left:20px;
}
```
